[tool.poetry]
name = "jamtestvectors"
version = "0.1.0"
description = ""
authors = ["dikshant441-chainscore <dikshant@chainscore.finance>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
